name: Demo.Inventory.Ingestion
concurrency: demo-inventory-ingestion

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch:

env:
  DotNetVersion: 6.0.x
  PackagePath: ./published
  ProjectName: Demo.Inventory.Ingestion.Functions
  FunctionAppName: inventorying
  ArtifactName: funcapp
  ResourceGroupName: cc-rg-inventorying
  ResourceGroupLocation: australiasoutheast
  
jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build, test and publish function app
        uses: Cheranga/GitHubActions/restorebuildtestpublish@master
        with:
          dotnetVersion: ${{ env.DotNetVersion }}
          projectName: ${{ env.ProjectName }}
          artifactName: ${{ env.ArtifactName }}
          
  Deploy:    
    name: DEV
    uses: ./.github/workflows/deploy.yml
    needs: CI
    with:
      environment: dev
      functionAppName: inventorying
      storageName: sginventorying
      resourceGroupName: cc-rg-inventorying
      location: australiasoutheast
      category: nonprod
      queues: inventory-changes
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
          
          

# This was working successfully to deploy Azure resources    
#  Deploy:
#    name: Deploy
#    needs: CI
#    runs-on: ubuntu-latest
#    env:
#      EnvironmentName: dev
#      Category: nonprod
#      Queues: inventory-changes
#    steps:          
#      - name: Vanilla Function App
#        uses: Cheranga/GitHubActions/vanillafunctionapp@master
#        with:
#          credentials: ${{ secrets.AZURE_CREDENTIALS }}
#          deploymentName: ${{ github.run_number }}-${{ env.FunctionAppName }}
#          environmentName: dev
#          resourceGroupName: ${{ env.ResourceGroupName }}
#          functionAppName: ${{ env.FunctionAppName }}
#          location: ${{ env.ResourceGroupLocation }}
#          category: nonprod          