name: Build

on:
  workflow_call:
    inputs:      
      projectName:
        required: true
        type: string
      dotnetVersion:
        required: true
        type: string
      artifactName:
        required: true
        type: string        

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build, test and publish function app
        uses: Cheranga/GitHubActions/restorebuildtestpublish@master
        with:
          dotnetVersion: ${{ inputs.dotNetVersion }}
          projectName: ${{ inputs.projectName }}
          artifactName: ${{ inputs.artifactName }}