name: Demo.Inventory.Ingestion
concurrency: demo-inventory-ingestion

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch:

env:
  DotNetVersion: 6.0.x
  PackagePath: ./published
  ProjectName: Demo.Inventory.Ingestion.Functions
  FunctionAppName: inventorying
  ArtifactName: funcapp
  ResourceGroupName: cc-rg-inventorying
  ResourceGroupLocation: australiasoutheast
  
jobs:
  CI:
    name: build test and publish
    runs-on: ubuntu-latest
    steps:
      - name: Build, test and publish function app
        uses: Cheranga/GitHubActions/restorebuildtestpublish@master
        with:
          dotnetVersion: ${{ env.DotNetVersion }}
          projectName: ${{ env.ProjectName }}
          artifactName: ${{ env.ArtifactName }}  
  Deploy:
    name: deploy resources
    needs: CI
    uses: ./.github/workflows/deploy.yml    
    with:
      environmentName: dev
      functionAppName: inventorying
      resourceGroupName: cc-rg-inventorying
      location: australiasoutheast
      category: nonprod
      queues: inventory-changes
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}