name: provisionresources

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      projectName:
        required: true
        type: string
      functionAppName:
        required: true
        type: string
      storageName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      location:
        required: true
        type: string
      category:
        required: true
        type: string
    secrets:
      credentials:
        required: true

jobs:     
  provisionresources:
    name: ${{ inputs.functionAppName }} 
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Vanilla Function App
        uses: Cheranga/GitHubActions/vanillafunctionapp@master
        with:
          credentials: ${{ secrets.credentials }}
          deploymentName: ${{ github.run_number }}-${{ inputs.functionAppName }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          functionAppName: ${{ inputs.functionAppName }}
          storageName: ${{ inputs.storageName }}
          location: ${{ inputs.location }}
          category: ${{ inputs.category }}

      - name: Create Queues
        uses: Cheranga/GitHubActions/storageaccount@master
        with:
          credentials: ${{secrets.credentials}}
          deploymentName: ${{ github.run_number }}-storage-account-updates
          resourceGroupName: ${{ inputs.resourceGroupName }}
          name: ${{ inputs.storageName }}
          location: ${{inputs.location}}
          storageType: ${{ inputs.category }}
          queues: inventory-changes
          blobContainers: demo-event,demo-inventory

      - name: Setup RBAC to Queue
        uses: Cheranga/GitHubActions/assignrbactostorage@master
        with:
          deploymentName: ${{ github.run_number }}-assign-queue-rbac
          resourceGroupName: ${{ inputs.resourceGroupName }}
          credentials: ${{secrets.credentials}}
          storageAccountName: ${{ inputs.storageName }}
          accessibility: queue_read_write
          friendlyName: ${{ inputs.functionAppName }}
          functionAppName: ${{ inputs.functionAppName }}

      - name: Setup RBAC to blobs
        uses: Cheranga/GitHubActions/assignrbactostorage@master
        with:
          deploymentName: ${{ github.run_number }}-assign-queue-rbac
          resourceGroupName: ${{ inputs.resourceGroupName }}
          credentials: ${{secrets.credentials}}
          storageAccountName: ${{ inputs.storageName }}
          accessibility: blob_contributor
          friendlyName: ${{ inputs.functionAppName }}
          functionAppName: ${{ inputs.functionAppName }}          

      - name: Setup RBAC to tables
        uses: Cheranga/GitHubActions/assignrbactostorage@master
        with:
          deploymentName: ${{ github.run_number }}-assign-queue-rbac
          resourceGroupName: ${{ inputs.resourceGroupName }}
          credentials: ${{secrets.credentials}}
          storageAccountName: ${{ inputs.storageName }}
          accessibility: table_write
          friendlyName: ${{ inputs.functionAppName }}
          functionAppName: ${{ inputs.functionAppName }}                

      - name: Update function app settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash                 
            az functionapp config appsettings set --name ${{ inputs.functionAppName }} --resource-group ${{ inputs.resourceGroupName }} --settings \
            "Environment=production" \
            "AcceptInventorySettings__Account=${{ inputs.storageName }}" \
            "AcceptInventorySettings__Category=Inventory" \
            "AcceptInventorySettings__Queue=inventory-changes" \
            "SourceInventorySettings__Account=${{ inputs.storageName }}" \
            "SourceInventorySettings__Category=Inventory" \
            "SourceInventorySettings__container=demo-event" \
            "DestinationInventorySettings__Account=${{ inputs.storageName }}" \
            "DestinationInventorySettings__Category=Inventory" \
            "DestinationInventorySettings__container=demo-inventory" \

      - name: Deploy code to function app
        uses: Cheranga/GitHubActions/deploydotnetfunctionapp@master
        with:
          credentials: ${{secrets.credentials}}
          dotnetVersion: 6.0.x
          projectName: ${{ inputs.projectName }}
          functionAppName: ${{ inputs.functionAppName }}