name: Demo.Inventory.Ingestion
concurrency: demo-inventory-ingestion

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch:

jobs:
  CI:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      projectName: Demo.Inventory.Ingestion.Functions
      dotnetVersion: 6.0.x
      artifactName: funcapp