name: Demo.Inventory.Ingestion
concurrency: demo-inventory-ingestion

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch:

jobs:
  CI:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      projectName: Demo.Inventory.Ingestion.Functions
      dotnetVersion: 6.0.x
      artifactName: funcapp
  Deploy:
    name: Deploy
    needs: CI
    environment:
      name: DEV
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      projectName: Demo.Inventory.Ingestion.Functions
      functionAppName: inventoryingdev
      storageName: sginventoryingdev
      resourceGroupName: cc-rg-inventorying-dev
      location: australiasoutheast
      category: nonprod
      queues: inventory-changes  
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}